/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "小飞猪的博客",
  "description": "我以为忘了想念",
  "base": "/YE/",
  "headTags": [],
  "pages": [
    {
      "title": "手把手教你轻松手写防抖和节流🔥",
      "frontmatter": {
        "title": "手把手教你轻松手写防抖和节流🔥",
        "date": "2023-1-1",
        "categories": [
          "前端"
        ],
        "tags": [
          "JavaScript",
          "手写"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/1.html",
      "relativePath": "blogs/1.md",
      "key": "v-2882827c",
      "path": "/blogs/1.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/tu1.gif",
        "heroText": "小飞猪",
        "bgImage": "/tu2.jpg",
        "bgImageStyle": {
          "height": "100%",
          "boxShadow": "0 15px 18px rgba(0,0,0,0.2)"
        },
        "heroImageStyle": {
          "maxHeight": "300px",
          "display": "block",
          "borderRadius": "19% 81% 23% 77% / 44% 57% 43% 56%",
          "boxShadow": "0 15px 18px rgba(0,0,0,0.2)"
        }
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-5651ea9c",
      "path": "/"
    },
    {
      "title": "🔥",
      "frontmatter": {
        "title": "🔥",
        "date": "2023-1-1",
        "categories": [
          11
        ],
        "tags": [
          "JavaScript",
          "手写"
        ],
        "sticky": 1
      },
      "regularPath": "/blogs/2.html",
      "relativePath": "blogs/2.md",
      "key": "v-7ae1391c",
      "path": "/blogs/2.html"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "JavaScript Tags"
      },
      "regularPath": "/tag/JavaScript/",
      "key": "v-7a5f6990",
      "path": "/tag/JavaScript/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "手写 Tags"
      },
      "regularPath": "/tag/%E6%89%8B%E5%86%99/",
      "key": "v-de8294a6",
      "path": "/tag/手写/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "11 Categories"
      },
      "regularPath": "/categories/11/",
      "key": "v-35a4d431",
      "path": "/categories/11/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "前端 Categories"
      },
      "regularPath": "/categories/%E5%89%8D%E7%AB%AF/",
      "key": "v-14bbbf36",
      "path": "/categories/前端/"
    }
  ],
  "themeConfig": {
    "author": "ye",
    "logo": "/tu1.gif",
    "authorAvatar": "/tu1.gif",
    "type": "blog",
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "小飞猪的博客",
        "items": [
          {
            "text": "掘金",
            "link": "https://juejin.cn/user/233526039432445"
          },
          {
            "text": "Github",
            "link": "https://github.com/Xusssyyy"
          }
        ]
      }
    ],
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "博客"
      },
      "tag": {
        "location": 4,
        "text": "Tag"
      }
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}