/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "JavaScript": {
      "key": "JavaScript",
      "scope": "tags",
      "path": "/tag/JavaScript/",
      "pageKeys": [
        "v-2882827c",
        "v-7ae1391c"
      ]
    },
    "手写": {
      "key": "手写",
      "scope": "tags",
      "path": "/tag/手写/",
      "pageKeys": [
        "v-2882827c",
        "v-7ae1391c"
      ]
    }
  },
  "categories": {
    "11": {
      "key": 11,
      "scope": "categories",
      "path": "/categories/11/",
      "pageKeys": [
        "v-7ae1391c"
      ]
    },
    "前端": {
      "key": "前端",
      "scope": "categories",
      "path": "/categories/前端/",
      "pageKeys": [
        "v-2882827c"
      ]
    }
  },
  "timeline": {}
}